typography_spectrum: 0.21030161692760885
color:
  brandStrength: 0.7244662295561284
  lightness: 0.01372296060435474
  saturation: 0.528573164716363
  rhythmicContrast: 0.020868578692898154
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.2770028274971992
name: The CPI Group
title: Look Deeper
description: >-
  Effective Decision-Making is the key to business
  success                                              We help point the way
